
# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: serverless-quoteImage

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  iamRoleStatements:
      -  Effect: "Allow"
         Action:
           - "dynamodb:GetItem"
         Resource: "arn:aws:dynamodb:us-west-2:071294546883:table/QuoteImages"
  runtime: nodejs6.10

# The `functions` block defines what code to deploy
functions:
  quoteImage:
    handler: handler.quoteImage
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: quoteImage
          method: post
          cors: true
