// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-west-2:e9148373-c5d5-4899-afcc-cafd7ffa8525',
    'aws_cognito_region': 'us-west-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'mottobook-hosting-mobilehub-551014980',
    'aws_content_delivery_bucket_region': 'us-west-2',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd1rwawz03d3ezr.cloudfront.net',
    'aws_mobile_analytics_app_id': '9939a351297b4bba99b9ec9c7e3f48bf',
    'aws_project_id': '26900acf-d6f8-4055-b2d3-ada92297c54e',
    'aws_project_name': 'MottoBook',
    'aws_project_region': 'us-west-2',
    'aws_resource_name_prefix': 'mottobook-mobilehub-551014980',
}

export default awsmobile;
